services:
  frontend:
    build:
      context: ./
    depends_on:
      - backend
    ports:
      - 3500:3500
  backend:
    build:
      context: backend
      target: builder
    env_file: ./backend/.flaskenv
    # SIGINT is required for flask to halt operations
    # gracefully.
    stop_signal: SIGINT
    ports:
      - 8000:8000